tunnel: 5234719b-4568-4d86-9e1d-3ac70b761e3c
credentials-file: /etc/cloudflared/credentials.json


ingress:
- hostname: portfolio.jonmaxjara.space
  service: http://app-prod:80
- service: http_status:404
